steps:
  - name: "gcr.io/cloud-builders/docker"
    id: build
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker build -t gcr.io/exalted-point-220022/$REPO_NAME:$COMMIT_SHA .",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: push
    args: ["push", "gcr.io/exalted-point-220022/$REPO_NAME:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/kubectl"
    waitFor:
      - push
    id: deploy
    args:
      - "set"
      - "image"
      - "deployment/myapp"
      - "myapp=gcr.io/exalted-point-220022/$REPO_NAME:$COMMIT_SHA"