apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp/ID/nodepp:1.0
    spec:
      containers:
      - name: nodeapp
        image: gcr.io
        ports:
        - containerPort: 3000