apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp/exalted-point-220022/nodeapp:1.0
    spec:
      containers:
      - name: nodeapp
        image: gcr.io/exalted-point-220022/nodeapp:1.0
        ports:
        - containerPort: 3000